apiVersion: v1
kind: Service
metadata:
  name: dev-deployment
  namespace: namespace-workflow-1741179447214
  labels:
    app.kubernetes.io/name: dev-deployment
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: dev-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80